/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as MarketsRouteImport } from './routes/markets'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FuturesRouteImport } from './routes/futures'
import { Route as EarnRouteImport } from './routes/earn'
import { Route as CopyRouteImport } from './routes/copy'
import { Route as BotsRouteImport } from './routes/bots'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TradeSymbolRouteImport } from './routes/trade.$symbol'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsRoute = MarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FuturesRoute = FuturesRouteImport.update({
  id: '/futures',
  path: '/futures',
  getParentRoute: () => rootRouteImport,
} as any)
const EarnRoute = EarnRouteImport.update({
  id: '/earn',
  path: '/earn',
  getParentRoute: () => rootRouteImport,
} as any)
const CopyRoute = CopyRouteImport.update({
  id: '/copy',
  path: '/copy',
  getParentRoute: () => rootRouteImport,
} as any)
const BotsRoute = BotsRouteImport.update({
  id: '/bots',
  path: '/bots',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeSymbolRoute = TradeSymbolRouteImport.update({
  id: '/trade/$symbol',
  path: '/trade/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bots': typeof BotsRoute
  '/copy': typeof CopyRoute
  '/earn': typeof EarnRoute
  '/futures': typeof FuturesRoute
  '/login': typeof LoginRoute
  '/markets': typeof MarketsRoute
  '/signup': typeof SignupRoute
  '/wallet': typeof WalletRoute
  '/trade/$symbol': typeof TradeSymbolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bots': typeof BotsRoute
  '/copy': typeof CopyRoute
  '/earn': typeof EarnRoute
  '/futures': typeof FuturesRoute
  '/login': typeof LoginRoute
  '/markets': typeof MarketsRoute
  '/signup': typeof SignupRoute
  '/wallet': typeof WalletRoute
  '/trade/$symbol': typeof TradeSymbolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bots': typeof BotsRoute
  '/copy': typeof CopyRoute
  '/earn': typeof EarnRoute
  '/futures': typeof FuturesRoute
  '/login': typeof LoginRoute
  '/markets': typeof MarketsRoute
  '/signup': typeof SignupRoute
  '/wallet': typeof WalletRoute
  '/trade/$symbol': typeof TradeSymbolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bots'
    | '/copy'
    | '/earn'
    | '/futures'
    | '/login'
    | '/markets'
    | '/signup'
    | '/wallet'
    | '/trade/$symbol'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bots'
    | '/copy'
    | '/earn'
    | '/futures'
    | '/login'
    | '/markets'
    | '/signup'
    | '/wallet'
    | '/trade/$symbol'
  id:
    | '__root__'
    | '/'
    | '/bots'
    | '/copy'
    | '/earn'
    | '/futures'
    | '/login'
    | '/markets'
    | '/signup'
    | '/wallet'
    | '/trade/$symbol'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BotsRoute: typeof BotsRoute
  CopyRoute: typeof CopyRoute
  EarnRoute: typeof EarnRoute
  FuturesRoute: typeof FuturesRoute
  LoginRoute: typeof LoginRoute
  MarketsRoute: typeof MarketsRoute
  SignupRoute: typeof SignupRoute
  WalletRoute: typeof WalletRoute
  TradeSymbolRoute: typeof TradeSymbolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/futures': {
      id: '/futures'
      path: '/futures'
      fullPath: '/futures'
      preLoaderRoute: typeof FuturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earn': {
      id: '/earn'
      path: '/earn'
      fullPath: '/earn'
      preLoaderRoute: typeof EarnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copy': {
      id: '/copy'
      path: '/copy'
      fullPath: '/copy'
      preLoaderRoute: typeof CopyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bots': {
      id: '/bots'
      path: '/bots'
      fullPath: '/bots'
      preLoaderRoute: typeof BotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade/$symbol': {
      id: '/trade/$symbol'
      path: '/trade/$symbol'
      fullPath: '/trade/$symbol'
      preLoaderRoute: typeof TradeSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BotsRoute: BotsRoute,
  CopyRoute: CopyRoute,
  EarnRoute: EarnRoute,
  FuturesRoute: FuturesRoute,
  LoginRoute: LoginRoute,
  MarketsRoute: MarketsRoute,
  SignupRoute: SignupRoute,
  WalletRoute: WalletRoute,
  TradeSymbolRoute: TradeSymbolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
